package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {
    
    static final long serialVersionUID = 1L;

    private String name;
    private int age;
    private double currentSalary;
    private int experienceInYears;
    
    public Applicant(){}

    public Applicant(String name, int age, Double currentSalary, int experienceInYears) {
        this.name = name;
        this.age = age;
        this.currentSalary = currentSalary;
        this.experienceInYears = experienceInYears;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Double getCurrentSalary() {
        return currentSalary;
    }

    public void setCurrentSalary(Double currentSalary) {
        this.currentSalary = currentSalary;
    }

    public int getExperienceInYears() {
        return experienceInYears;
    }

    public void setExperienceInYears(int experienceInYears) {
        this.experienceInYears = experienceInYears;
    }
}
