package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
  private Status status ;
    
    private String message;

    public Message(Status status, String message) {
        this.status = status;
        this.message = message;
    }
    
    public void setMessage(String msg){
        this.message = msg;
    }
    
    public String getMessage(){
        return message;
    }
    
    public void setStatus(Status status){
        this.status = status;
    }
    
    public Status getStatus(){
        return status;
    }


}