package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Product() {
    }

private String name;
    private String type;

    private String label;

    public Product(String name, String type) {
        this.name = name;
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }


}