package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SuggestedRole implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SuggestedRole() {
    }

    private String role;

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }


}